fieldLayouts:
  58043034-dbb5-42e2-a340-e61512385075:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 22833403-13bf-4fea-b6dc-4f282d107f8b
            warning: null
            width: 100
        name: Content
        uid: 1e6ab7b0-8aa8-445e-a553-c828c6e992a4
handle: home
hasTitleField: false
name: Home
section: 23364c3c-91a1-47c7-bb2f-000b8fa1b09e # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
