defaultPlacement: end
enableVersioning: false
handle: about
name: About
propagationMethod: all
siteSettings:
  93f4b0cf-62cc-4564-8ab1-d51fa2934e14: # HatchDSM
    enabledByDefault: true
    hasUrls: true
    template: about/_entry
    uriFormat: about
type: single
